### ISSUE TITLE
Context 

### ISSUE THREAD

**Issue by yunlongz** [just4fun/uestc-bbs-react-native#3]
Menu.js. This.context.menuActions  is undefined ？

**Comment by just4fun** [comment]
Did you encountered this error? `This.context.menuActions` is designed by old version of [react-native-side-menu](https://github.com/react-native-fellowship/react-native-side-menu), and the author put it into the `context`, hence the code below in `Menu.js`.

```javascript
Menu.contextTypes = {
  menuActions: React.PropTypes.object.isRequired
};
```

I think we won't encounter this error since I haven't upgraded `react-native-side-menu` since I started this project. Could you remove your `node_modules` and clean you project in Xcode, then install and run in Xcode again? Or could you provide more information such as your node version, etc.

**Comment by just4fun** [comment]
Close this issue since it seems like environment related.
