### ISSUE TITLE
View was rendered with explicitly set width/height but with a 0 flexBasis

### ISSUE THREAD

**Issue by namthang** [just4fun/uestc-bbs-react-native#6]
Hi author.
Thanks so much for your git project.
After i run project with xcode. i have a notice with content:"View was rendered with explicitly set width/height but with a 0 flexBasis"
What this means and how to fix ??
Thanks.

**Comment by just4fun** [comment]
Hi there,

Could you please attach a screenshot with the problem? I wanna know whether it's just warning in simulator or an error in Xcode with building failed.

**Comment by namthang** [comment]
Thanks for reply. 
<img width="379" alt="screen shot 2016-12-20 at 5 41 45 pm" src="https://cloud.githubusercontent.com/assets/7126246/21347545/abd6f9a8-c6db-11e6-9c05-e68a51dbc2d8.png">

**Comment by just4fun** [comment]
The iOS in my Xcode is still 10.0, and my app works OK on it.

Before I finish upgrading my Xcode, could you please try to update `flex` to `flexGrow` where has width or height set explicitly according to the error message? You can also refer [this](http://stackoverflow.com/questions/41004883/react-native-view-was-rendered-with-explicitly-set-width-height-but-with-a-0-fle) first.

**Comment by just4fun** [comment]
@namthang I have verified on iOS 10.2 as your screenshot displayed, it works well.

After investigation, I found this error is released in this [commit](https://github.com/facebook/react-native/commit/a96b4ab5a0d59a8ac3861506589a1cc449dfe7a5) of `react-native`, so I think it's caused by different version of `react-native`.

Can you update `"react-native": "^0.34.1",` in `package.json` to `"react-native": "~0.34.1",` then try again?

**Comment by namthang** [comment]
@just4fun  Sorry, sorry for the delayed response. 
i use your startkit for my new project react-native and, when i install, i have to upgrade the whole package, in my package.json "react-native": "^0.39.2". 
I think that's why.
Thanks so much for your ardour.

**Comment by just4fun** [comment]
Yeah this error message is involved in latest react-native, glad you got it figured out. 😃
